const translations = {
    en: {
        bio: "Solo Quest Modder And Game Maker",
        moddedApks: "Modded Apks",
        tagDiscord: "FREE GET BY DISCORD",
        discordCommunity: "Discord Community",
        tvMenuLib: "TvMenuLib (1.0.0)",
        tagFree: "FREE",
        tvMenuPCVR: "TvMenuPCVR (in dev, join discord boi)",
        tagPaid: "PAID/GET BY DISCORD",
        moddedGtag: "Modded Gtag By Tvman",
        faqTitle: "Frequently Asked Questions",
        faqDesc: "Got questions about mods, menus, or releases? Find quick answers to common questions below!",
        q1Name: "Q: How do I download/get the modded APKs?",
        q1Val: "A: All free modded APKs and project files are distributed directly through our Discord community server. Join the Discord to access the download channels.",
        q2Name: "Q: Is TvMenu Lib free to use?",
        q2Val: "A: Yes! TvMenu Lib is completely free and intended for modding Gorilla Tag copies and fan games. Check the library tab for instructions.",
        q3Name: "Q: When is TvMenuPCVR releasing?",
        q3Val: "A: TvMenuPCVR is currently untested and coming soon. Keep an eye on the Discord announcements channel for release dates and testing info!",
        q4Name: "Q: Who do I contact if I need support?",
        q4Val: "A: You can reach out via email at TvmanMods@proton.me or open a support ticket inside our Discord server.",
        creditsTitle: "Credits",
        creditsText: "Credits to StripesVr for making the first hub!",
        updates: "Updates",
        online: "Online",
        hubOnline: "Hub: Online",
        languageLabel: "Language",
        inServer: "in server",
        staticOverlay: "Static overlay",
        eyebrow: "TVMAN COMMAND",
        heroTitle: "Mods, libs, and the server — one hub.",
        heroCopy: "Free APKs and TvMenu Lib through Discord. Paid PCVR and Gtag builds live in the same room.",
        hotkeys: "Keys: D Discord · L Lib · S static",
        patchTitle: "Patch notes",
        patch1: "Version chip, last-seen embed, live pulse",
        patch2: "Blood trail, boot log, D/L/S hotkeys",
        patch3: "Pinned patch notes, static overlay, server online",
        widgetTitle: "Live Discord Server Widget",
        loadingTitle: "Tvman Hub",
        noteSupport: "Support: TvmanMods@proton.me",
        noteLib: "Lib download opens MediaFire, then join Discord for setup.",
        libDone: "TvMenu Lib Downloaded!",
        libBody: "Your MediaFire download has started in a new tab. Join the community Discord server to view the setup instructions!",
        libJoin: "JOIN THE DISCORD TO DO THE REST",
        updateHistory: "Update History",
        update1Title: "MediaFire & Discord Lib Flow Integration",
        update1Body: "Clicking TvMenu Lib now downloads the file via MediaFire and displays a prompt modal to join the Discord server for setup.",
        update2Title: "Command-center layout",
        update2Body: "Two-pane hub, new type, action cards, same links and languages."
    },
    es: {
        bio: "Modder Solitario de Quest y Creador de Juegos",
        moddedApks: "APKs Modificados",
        tagDiscord: "GRATIS POR DISCORD",
        discordCommunity: "Comunidad de Discord",
        tvMenuLib: "TvMenuLib (1.0.0)",
        tagFree: "GRATIS",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "PAGO / POR DISCORD",
        moddedGtag: "Gtag Modificado por Tvman",
        faqTitle: "Preguntas Frecuentes",
        faqDesc: "¿Tienes dudas sobre mods, menús o lanzamientos? ¡Encuentra respuestas rápidas abajo!",
        q1Name: "P: ¿Cómo descargo/consigo los APKs modificados?",
        q1Val: "R: Todos los APKs modificados y archivos de proyectos gratuitos se distribuyen directamente en nuestro servidor de Discord.",
        q2Name: "P: ¿Es TvMenu Lib gratis de usar?",
        q2Val: "R: ¡Sí! TvMenu Lib es completamente gratuito para modear copias de Gorilla Tag y fan games.",
        q3Name: "P: ¿Cuándo se lanza TvMenuPCVR?",
        q3Val: "R: TvMenuPCVR aún no está probado y llegará pronto. ¡Atentos a los anuncios de Discord!",
        q4Name: "P: ¿A quién contacto si necesito soporte?",
        q4Val: "R: Puedes contactarnos por correo a TvmanMods@proton.me o abrir un ticket en Discord.",
        creditsTitle: "Créditos",
        creditsText: "¡Créditos a StripesVr por hacer el primer hub!",
        updates: "Actualizaciones",
        online: "En línea",
        hubOnline: "Hub: En línea",
        languageLabel: "Idioma",
        inServer: "en el servidor",
        staticOverlay: "Estática",
        eyebrow: "TVMAN COMMAND",
        heroTitle: "Mods, libs y el servidor — un solo hub.",
        heroCopy: "APKs gratis y TvMenu Lib por Discord. PCVR y Gtag de pago en el mismo servidor.",
        hotkeys: "Teclas: D Discord · L Lib · S estática",
        patchTitle: "Notas del parche",
        patch1: "Chip de versión, embed last-seen, pulso en vivo",
        patch2: "Rastro de sangre, boot log, teclas D/L/S",
        patch3: "Notas fijadas, estática, online del server",
        widgetTitle: "Widget de Discord en vivo",
        loadingTitle: "Tvman Hub",
        noteSupport: "Soporte: TvmanMods@proton.me",
        noteLib: "La lib se descarga en MediaFire; entra a Discord para el setup.",
        libDone: "¡TvMenu Lib descargada!",
        libBody: "La descarga de MediaFire empezó en otra pestaña. Entra al Discord para el setup.",
        libJoin: "ENTRA AL DISCORD PARA EL RESTO",
        updateHistory: "Historial de actualizaciones",
        update1Title: "Integración MediaFire y Discord para la Lib",
        update1Body: "Al tocar TvMenu Lib se descarga por MediaFire y sale el modal para unirse a Discord.",
        update2Title: "Diseño command-center",
        update2Body: "Hub de dos paneles, tipografía nueva, mismas links e idiomas."
    },
    fr: {
        bio: "Moddeur Solo sur Quest et Créateur de Jeux",
        moddedApks: "APK Moddés",
        tagDiscord: "GRATUIT VIA DISCORD",
        discordCommunity: "Communauté Discord",
        tvMenuLib: "TvMenuLib (1.0.0)",
        tagFree: "GRATUIT",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "PAYANT / VIA DISCORD",
        moddedGtag: "Gtag Moddé par Tvman",
        faqTitle: "Foire Aux Questions",
        faqDesc: "Des questions sur les mods ou les menus ? Trouvez des réponses rapides ci-dessous !",
        q1Name: "Q : Comment télécharger les APK moddés ?",
        q1Val: "R : Tous les fichiers gratuits sont distribués directement via notre serveur Discord.",
        q2Name: "Q : TvMenu Lib est-il gratuit ?",
        q2Val: "R : Oui ! TvMenu Lib est entièrement gratuit pour le modding de jeux dérivés.",
        q3Name: "Q : Quand sortira TvMenuPCVR ?",
        q3Val: "R : TvMenuPCVR arrive bientôt. Restez à l'écoute sur les annonces Discord !",
        q4Name: "Q : Qui contacter en cas de problème ?",
        q4Val: "R : Contactez-nous par e-mail à TvmanMods@proton.me ou via un ticket sur Discord.",
        creditsTitle: "Crédits",
        creditsText: "Crédits à StripesVr pour avoir créé le premier hub !",
        updates: "Mises à jour",
        online: "En ligne",
        hubOnline: "Hub : En ligne"
    },
    de: {
        bio: "Solo Quest Modder und Spieleentwickler",
        moddedApks: "Modifizierte APKs",
        tagDiscord: "KOSTENLOS ÜBER DISCORD",
        discordCommunity: "Discord Community",
        tvMenuLib: "TvMenuLib (1.0.0)",
        tagFree: "KOSTENLOS",
        tvMenuPCVR: "TvMenuPCVR",
        tagPaid: "BEZAHLT / ÜBER DISCORD",
        moddedGtag: "Modded Gtag von Tvman",
        faqTitle: "Häufig gestellte Fragen",
        faqDesc: "Fragen zu Mods, Menüs oder Releases? Hier findest du schnelle Antworten!",
        q1Name: "F: Wie lade ich die modifizierten APKs herunter?",
        q1Val: "A: Alle kostenlosen APKs werden direkt über unseren Discord-Server verteilt.",
        q2Name: "F: Ist TvMenu Lib kostenlos?",
        q2Val: "A: Ja! TvMenu Lib ist völlig kostenlos für das Modden von Fan-Spielen.",
        q3Name: "F: Wann erscheint TvMenuPCVR?",
        q3Val: "A: TvMenuPCVR folgt bald. Behalte die Discord-Ankündigungen im Auge!",
        q4Name: "F: An wen wende ich mich bei Support?",
        q4Val: "A: Schreibe eine E-Mail an TvmanMods@proton.me oder öffne ein Ticket auf Discord.",
        creditsTitle: "Mitwirkende",
        creditsText: "Credits an StripesVr für die Erstellung des ersten Hubs!",
        updates: "Updates",
        online: "Online",
        hubOnline: "Hub: Online"
    },
    it: { bio: "Solo Quest Modder And Game Maker", moddedApks: "Modded Apks", tagDiscord: "FREE GET BY DISCORD", discordCommunity: "Discord Community", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "FREE", tvMenuPCVR: "TvMenuPCVR", tagPaid: "PAID/GET BY DISCORD", moddedGtag: "Modded Gtag By Tvman", faqTitle: "Frequently Asked Questions", faqDesc: "Got questions about mods, menus, or releases? Find quick answers to common questions below!", q1Name: "Q: How do I download/get the modded APKs?", q1Val: "A: All free modded APKs and project files are distributed directly through our Discord community server.", q2Name: "Q: Is TvMenu Lib free to use?", q2Val: "A: Yes!", q3Name: "Q: When is TvMenuPCVR releasing?", q3Val: "A: Coming soon.", q4Name: "Q: Who do I contact if I need support?", q4Val: "A: Discord or email.", creditsTitle: "Credits", creditsText: "Credits to StripesVr for making the first hub!", updates: "Updates", online: "Online", hubOnline: "Hub: Online" },
    pt: { bio: "Modder de Solo Quest e Criador de Jogos", moddedApks: "APKs Modificados", tagDiscord: "GRÁTIS VIA DISCORD", discordCommunity: "Comunidade Discord", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "GRÁTIS", tvMenuPCVR: "TvMenuPCVR", tagPaid: "PAGO / VIA DISCORD", moddedGtag: "Gtag Modificado por Tvman", faqTitle: "Perguntas Frequentes", faqDesc: "Tem dúvidas? Encontre respostas abaixo!", q1Name: "P: Como baixar os APKs?", q1Val: "R: No Discord.", q2Name: "P: TvMenu Lib é grátis?", q2Val: "R: Sim!", q3Name: "P: Quando lança o TvMenuPCVR?", q3Val: "R: Em breve.", q4Name: "P: Suporte?", q4Val: "R: Discord.", creditsTitle: "Créditos", creditsText: "Créditos a StripesVr!", updates: "Atualizações", online: "Online", hubOnline: "Hub: Online" },
    ru: { bio: "Quest Моддер и Разработчик Игр", moddedApks: "Модифицированные APK", tagDiscord: "БЕСПЛАТНО В DISCORD", discordCommunity: "Discord Сообщество", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "БЕСПЛАТНО", tvMenuPCVR: "TvMenuPCVR", tagPaid: "ПЛАТНО / ЧЕРЕЗ DISCORD", moddedGtag: "Мод Gtag от Tvman", faqTitle: "Часто задаваемые вопросы", faqDesc: "Ответы на вопросы ниже!", q1Name: "В: Как скачать APK?", q1Val: "О: Через Discord.", q2Name: "В: TvMenu Lib бесплатный?", q2Val: "О: Да!", q3Name: "В: Когда выйдет TvMenuPCVR?", q3Val: "О: Скоро.", q4Name: "В: Поддержка?", q4Val: "О: Discord.", creditsTitle: "Кредиты", creditsText: "Спасибо StripesVr!", updates: "Обновления", online: "Онлайн", hubOnline: "Хаб: Онлайн" },
    ja: { bio: "ソロクエストモッダー＆ゲームメーカー", moddedApks: "Modded APK", tagDiscord: "DISCORDで無料入手", discordCommunity: "Discord コミュニティ", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "無料", tvMenuPCVR: "TvMenuPCVR", tagPaid: "有料 / DISCORD", moddedGtag: "TvmanによるModded Gtag", faqTitle: "よくある質問", faqDesc: "質問はこちら", q1Name: "Q: APKのダウンロード方法は？", q1Val: "A: Discordサーバーから。", q2Name: "Q: TvMenu Libは無料ですか？", q2Val: "A: はい！", q3Name: "Q: TvMenuPCVRのリリース日は？", q3Val: "A: 近日公開。", q4Name: "Q: サポートの連絡先は？", q4Val: "A: Discordまたはメール。", creditsTitle: "クレジット", creditsText: "最初のハブを作ってくれたStripesVrに感謝！", updates: "アップデート", online: "オンライン", hubOnline: "ハブ: オンライン" },
    ko: { bio: "솔로 퀘스트 모더 및 게임 메이커", moddedApks: "모드된 APK", tagDiscord: "디스코드에서 무료 받기", discordCommunity: "디스코드 커뮤니티", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "무료", tvMenuPCVR: "TvMenuPCVR", tagPaid: "유료 / 디스코드", moddedGtag: "Tv만의 모드된 Gtag", faqTitle: "자주 묻는 질문", faqDesc: "질문과 답변", q1Name: "Q: APK 다운로드 방법?", q1Val: "A: 디스코드에서.", q2Name: "Q: TvMenu Lib 무료인가요?", q2Val: "A: 네!", q3Name: "Q: TvMenuPCVR 출시일?", q3Val: "A: 곧 출시.", q4Name: "Q: 지원 문의?", q4Val: "A: 디스코드.", creditsTitle: "크레딧", creditsText: "첫 번째 허브를 만들어준 StripesVr에게 크레딧을!", updates: "업데이트", online: "온라인", hubOnline: "허브: 온라인" },
    zh: { bio: "单人 Quest 模组制作者兼游戏开发者", moddedApks: "修改版 APK", tagDiscord: "通过 DISCORD 免费获取", discordCommunity: "Discord 社区", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "免费", tvMenuPCVR: "TvMenuPCVR", tagPaid: "付费 / 通过 DISCORD", moddedGtag: "Tvman 的修改版 Gtag", faqTitle: "常见问题", faqDesc: "查看常见问题解答！", q1Name: "问：如何下载修改版 APK？", q1Val: "答：通过我们的 Discord 社区服务器分发。", q2Name: "问：TvMenu Lib 是免费的吗？", q2Val: "答：是的！", q3Name: "问：TvMenuPCVR 何时发布？", q3Val: "答：即将推出。", q4Name: "问：如何联系支持？", q4Val: "答：通过 Discord。", creditsTitle: "鸣谢", creditsText: "感谢 StripesVr 制作了第一个 Hub！", updates: "更新日志", online: "在线", hubOnline: "Hub: 在线" },
    ar: { bio: "صانع ألعاب ومعدل كويست منفرد", moddedApks: "APKs معدلة", tagDiscord: "مجاناً عبر ديسكورد", discordCommunity: "مجتمع ديسكورد", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "مجاني", tvMenuPCVR: "TvMenuPCVR", tagPaid: "مدفوع / عبر ديسكورد", moddedGtag: "Gtag معدل بواسطة Tvman", faqTitle: "الأسئلة الشائعة", faqDesc: "اعثر على إجابات سريعة أدناه!", q1Name: "س: كيف أقوم بتنزيل APKs المعدلة؟", q1Val: "ج: عبر خادم ديسكورد.", q2Name: "س: هل TvMenu Lib مجاني للاستخدام؟", q2Val: "ج: نعم!", q3Name: "س: متى سيصدر TvMenuPCVR؟", q3Val: "ج: قريباً.", q4Name: "س: بمن أتصل للدعم؟", q4Val: "ج: عبر ديسكورد.", creditsTitle: "الرصيد", creditsText: "شكراً لـ StripesVr على إنشاء المحور الأول!", updates: "التحديثات", online: "متصل", hubOnline: "المحور: متصل" },
    hi: { bio: "سولو क्वेस्ट मॉडder और गेम मेकर", moddedApks: "मॉडड APKs", tagDiscord: "डिस्कॉर्ड द्वारा मुफ़्त पाएं", discordCommunity: "डिस्कॉर्ड कम्युनिटी", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "मुफ़्त", tvMenuPCVR: "TvMenuPCVR", tagPaid: "पायड / डिस्कॉर्ड द्वारा", moddedGtag: "Tvman द्वारा मॉडड Gtag", faqTitle: "अक्सर पूछे जाने वाले प्रश्न", faqDesc: "प्रशन और उत्तर नीचे देखें!", q1Name: "प्र: APKs कैसे डाउनलोड करें?", q1Val: "उ: हमारे डिस्कॉर्ड सर्वर से।", q2Name: "प्र: क्या TvMenu Lib मुफ़्त है?", q2Val: "उ: हाँ!", q3Name: "प्र: TvMenuPCVR कब रिलीज़ होगा?", q3Val: "उ: जल्द ही आ रहा है।", q4Name: "प्र: सपोर्ट के लिए संपर्क?", q4Val: "उ: डिस्कॉर्ड पर।", creditsTitle: "क्रेडिट्स", creditsText: "पहला हब बनाने के लिए StripesVr को क्रेडिट!", updates: "अपडेट", online: "ऑनलाइन", hubOnline: "हब: ऑनलाइन" },
    tr: { bio: "Solo Quest Modcusu ve Oyun Yapımcısı", moddedApks: "Modlu APK'lar", tagDiscord: "DİSCORD İLE ÜCRETSİZ AL", discordCommunity: "Discord Topluluğu", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "ÜCRETSİZ", tvMenuPCVR: "TvMenuPCVR", tagPaid: "ÜCRETLİ / DİSCORD", moddedGtag: "Tvman'den Modlu Gtag", faqTitle: "Sıkça Sorulan Sorular", faqDesc: "Hızlı yanıtlar aşağıda!", q1Name: "S: Modlu APK'ları nasıl indiririm?", q1Val: "C: Discord sunucumuzdan.", q2Name: "S: TvMenu Lib ücretsiz mi?", q2Val: "C: Evet!", q3Name: "S: TvMenuPCVR ne zaman çıkıyor?", q3Val: "C: Yakında.", q4Name: "S: Destek için kiminle iletişime geçmeliyim?", q4Val: "C: Discord.", creditsTitle: "Emeği Geçenler", creditsText: "İlk hub'ı yaptığı için StripesVr'ye teşekkürler!", updates: "Güncellemeler", online: "Çevrimiçi", hubOnline: "Hub: Çevrimiçi" },
    nl: { bio: "Solo Quest Modder en Spelmaker", moddedApks: "Gemodde APK's", tagDiscord: "GRATIS VIA DISCORD", discordCommunity: "Discord-gemeenschap", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "GRATIS", tvMenuPCVR: "TvMenuPCVR", tagPaid: "BETAALD / VIA DISCORD", moddedGtag: "Gemodde Gtag door Tvman", faqTitle: "Veelgestelde Vragen", faqDesc: "Vind hier snel antwoorden!", q1Name: "V: Hoe download ik de APK's?", q1Val: "A: Via Discord.", q2Name: "V: Is TvMenu Lib gratis?", q2Val: "A: Ja!", q3Name: "V: Wanneer komt TvMenuPCVR uit?", q3Val: "A: Binnenkort.", q4Name: "V: Contact?", q4Val: "A: Discord.", creditsTitle: "Credits", creditsText: "Credits voor StripesVr!", updates: "Updates", online: "Online", hubOnline: "Hub: Online" },
    pl: { bio: "Modder Solo Quest i Twórca Gier", moddedApks: "Zmodyfikowane APK", tagDiscord: "DARMOWE PRZEZ DISCORDA", discordCommunity: "Społeczność Discord", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "DARMOWE", tvMenuPCVR: "TvMenuPCVR", tagPaid: "PŁATNE / PRZEZ DISCORDA", moddedGtag: "Modowany Gtag od Tvman", faqTitle: "Często Zadawane Pytania", faqDesc: "Znajdź odpowiedzi poniżej!", q1Name: "P: Jak pobrać pliki APK?", q1Val: "O: Przez nasz serwer Discord.", q2Name: "P: Czy TvMenu Lib jest darmowe?", q2Val: "O: Tak!", q3Name: "P: Kiedy premiera TvMenuPCVR?", q3Val: "O: Wkrótce.", q4Name: "P: Kontakt w sprawie wsparcia?", q4Val: "O: Discord.", creditsTitle: "Twórcy", creditsText: "Podziękowania dla StripesVr za stworzenie pierwszego huba!", updates: "Aktualizacje", online: "Online", hubOnline: "Hub: Online" },
    vi: { bio: "Làm Mod Solo Quest & Tạo Game", moddedApks: "APK Đã Mod", tagDiscord: "NHẬN MIỄN PHÍ QUA DISCORD", discordCommunity: "Cộng đồng Discord", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "MIỄN PHÍ", tvMenuPCVR: "TvMenuPCVR", tagPaid: "TRẢ PHÍ / QUA DISCORD", moddedGtag: "Gtag Mod bởi Tvman", faqTitle: "Các Câu Hỏi Thường Gặp", faqDesc: "Xem câu trả lời bên dưới!", q1Name: "H: Làm sao để tải APK mod?", q1Val: "Đ: Qua máy chủ Discord.", q2Name: "H: TvMenu Lib có miễn phí không?", q2Val: "Đ: Có!", q3Name: "H: Khi nào TvMenuPCVR ra mắt?", q3Val: "Đ: Sắp ra mắt.", q4Name: "H: Hỗ trợ?", q4Val: "Đ: Discord.", creditsTitle: "Tác giả", creditsText: "Cảm ơn StripesVr đã tạo hub đầu tiên!", updates: "Cập nhật", online: "Đang trực tuyến", hubOnline: "Hub: Trực tuyến" },
    th: { bio: "นัก mod Quest เดี่ยวและผู้สร้างเกม", moddedApks: "APK ที่ปรับแต่งแล้ว", tagDiscord: "รับฟรีทาง DISCORD", discordCommunity: "ชุมชน Discord", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "ฟรี", tvMenuPCVR: "TvMenuPCVR", tagPaid: "จ่ายเงิน / ผ่าน DISCORD", moddedGtag: "Gtag Mod โดย Tvman", faqTitle: "คำถามที่พบบ่อย", faqDesc: "หาคำตอบได้ด้านล่าง!", q1Name: "Q: ดาวน์โหลด APK ได้อย่างไร?", q1Val: "A: ผ่านเซิร์ฟเวอร์ Discord ของเรา", q2Name: "Q: TvMenu Lib ฟรีหรือไม่?", q2Val: "A: ใช่!", q3Name: "Q: TvMenuPCVR จะออกเมื่อไหร่?", q3Val: "A: เร็วๆ นี้", q4Name: "Q: ติดต่อซัพพอร์ต?", q4Val: "A: ผ่าน Discord", creditsTitle: "เครดิต", creditsText: "เครดิตถึง StripesVr สำหรับการทำ Hub แรก!", updates: "อัปเดต", online: "ออนไลน์", hubOnline: "Hub: ออนไลน์" },
    id: { bio: "Modder Quest Solo & Pembuat Game", moddedApks: "APK Mod", tagDiscord: "GRATIS VIA DISCORD", discordCommunity: "Komunitas Discord", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "GRATIS", tvMenuPCVR: "TvMenuPCVR", tagPaid: "BERBAYAR / VIA DISCORD", moddedGtag: "Gtag Mod oleh Tvman", faqTitle: "Pertanyaan yang Sering Diajukan", faqDesc: "Temukan jawaban cepat di bawah!", q1Name: "T: Bagaimana cara mengunduh APK mod?", q1Val: "J: Melalui server Discord kami.", q2Name: "T: Apakah TvMenu Lib gratis?", q2Val: "J: Ya!", q3Name: "T: Kapan TvMenuPCVR rilis?", q3Val: "J: Segera hadir.", q4Name: "T: Kontak dukungan?", q4Val: "J: Discord.", creditsTitle: "Kredit", creditsText: "Kredit untuk StripesVr!", updates: "Pembaruan", online: "Online", hubOnline: "Hub: Online" },
    uk: { bio: "Моддер Solo Quest та розробник ігор", moddedApks: "Модифіковані APK", tagDiscord: "БЕЗКОШТОВНО В DISCORD", discordCommunity: "Discord Спільнота", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "БЕЗКОШТОВНО", tvMenuPCVR: "TvMenuPCVR", tagPaid: "ПЛАТНО / ЧЕРЕЗ DISCORD", moddedGtag: "Мод Gtag від Tvman", faqTitle: "Часті запитання", faqDesc: "Знайдіть відповіді нижче!", q1Name: "З: Як завантажити APK?", q1Val: "В: Через наш сервер Discord.", q2Name: "З: Чи безкоштовний TvMenu Lib?", q2Val: "В: Так!", q3Name: "З: Коли вийде TvMenuPCVR?", q3Val: "В: Скоро.", q4Name: "З: Підтримка?", q4Val: "В: Discord.", creditsTitle: "Автори", creditsText: "Подяка StripesVr за створення першого хабу!", updates: "Оновлення", online: "Онлайн", hubOnline: "Хаб: Онлайн" },
    sv: { bio: "Solo Quest Moddare och Spelmakare", moddedApks: "Moddade APKs", tagDiscord: "GRATIS VIA DISCORD", discordCommunity: "Discord-gemenskap", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "GRATIS", tvMenuPCVR: "TvMenuPCVR", tagPaid: "BETALD / VIA DISCORD", moddedGtag: "Moddad Gtag av Tvman", faqTitle: "Vanliga Frågor", faqDesc: "Hitta svar nedan!", q1Name: "F: Hur laddar jag ner APKs?", q1Val: "S: Via Discord.", q2Name: "F: Är TvMenu Lib gratis?", q2Val: "S: Ja!", q3Name: "F: När släpps TvMenuPCVR?", q3Val: "S: Kommer snart.", q4Name: "F: Support?", q4Val: "S: Discord.", creditsTitle: "Credits", creditsText: "Tack till StripesVr!", updates: "Uppdateringar", online: "Online", hubOnline: "Hub: Online" },
    no: { bio: "Solo Quest Modder og Spillskaper", moddedApks: "Moddede APK-er", tagDiscord: "GRATIS VIA DISCORD", discordCommunity: "Discord-fellesskap", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "GRATIS", tvMenuPCVR: "TvMenuPCVR", tagPaid: "BETALT / VIA DISCORD", moddedGtag: "Modded Gtag av Tvman", faqTitle: "Ofte Stilte Spørsmål", faqDesc: "Finn svar nedenfor!", q1Name: "Spørsmål: Hvordan laste ned?", q1Val: "Svar: Via Discord.", q2Name: "Spørsmål: Er TvMenu Lib gratis?", q2Val: "Svar: Ja!", q3Name: "Spørsmål: Når kommer TvMenuPCVR?", q3Val: "Svar: Kommer snart.", q4Name: "Spørsmål: Støtte?", q4Val: "Svar: Discord.", creditsTitle: "Kreditter", creditsText: "Kreditter til StripesVr!", updates: "Oppdateringer", online: "Online", hubOnline: "Hub: Online" },
    da: { bio: "Solo Quest Modder og Spilskaber", moddedApks: "Moddede APK'er", tagDiscord: "GRATIS VIA DISCORD", discordCommunity: "Discord Fællesskab", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "GRATIS", tvMenuPCVR: "TvMenuPCVR", tagPaid: "BETALT / VIA DISCORD", moddedGtag: "Modded Gtag af Tvman", faqTitle: "Ofte Stillede Spørgsmål", faqDesc: "Find svar herunder!", q1Name: "Spørgsmål: Hvordan downloader man?", q1Val: "Svar: Via Discord.", q2Name: "Spørsmål: Er TvMenu Lib gratis?", q2Val: "Svar: Ja!", q3Name: "Spørsmål: Hvornår udkommer TvMenuPCVR?", q3Val: "Svar: Kommer snart.", q4Name: "Spørsmål: Support?", q4Val: "Svar: Discord.", creditsTitle: "Kreditter", creditsText: "Kreditter til StripesVr!", updates: "Opdateringer", online: "Online", hubOnline: "Hub: Online" },
    fi: { bio: "Solo Quest Modder ja Pelintekijä", moddedApks: "Modatut APK:t", tagDiscord: "ILMAISEKSI DISCORDIN KAUTTA", discordCommunity: "Discord-yhteisö", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "ILMAINEN", tvMenuPCVR: "TvMenuPCVR", tagPaid: "MAKSULLINEN / DISCORD", moddedGtag: "Modattu Gtag Tvmanilta", faqTitle: "Usein Kysytyt Kysymykset", faqDesc: "Löydä vastaukset alta!", q1Name: "K: Miten lataan APK:t?", q1Val: "V: Discord-palvelimeltamme.", q2Name: "K: Onko TvMenu Lib ilmainen?", q2Val: "V: Kyllä!", q3Name: "K: Milloin TvMenuPCVR julkaistaan?", q3Val: "V: Tulossa pian.", q4Name: "K: Tuki?", q4Val: "V: Discord.", creditsTitle: "Tekijät", creditsText: "Kiitokset StripesVrlle!", updates: "Päivitykset", online: "Paikalla", hubOnline: "Hub: Paikalla" },
    el: { bio: "Solo Quest Modder και Game Maker", moddedApks: "Modded APKs", tagDiscord: "ΔΩΡΕΑΝ ΜΕΣΩ DISCORD", discordCommunity: "Κοινότητα Discord", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "ΔΩΡΕΑΝ", tvMenuPCVR: "TvMenuPCVR", tagPaid: "ΕΠΙΘΕΤΙΚΟ / DISCORD", moddedGtag: "Modded Gtag από Tvman", faqTitle: "Συχνές Ερωτήσεις", faqDesc: "Βρείτε απαντήσεις παρακάτω!", q1Name: "Ε: Πώς κατεβάζω τα APKs;", q1Val: "Α: Μέσω Discord.", q2Name: "Ε: Είναι δωρεάν το TvMenu Lib;", q2Val: "Α: Ναι!", q3Name: "Ε: Πότε κυκλοφορεί το TvMenuPCVR;", q3Val: "Α: Σύντομα.", q4Name: "Ε: Υποστήριξη;", q4Val: "Α: Discord.", creditsTitle: "Συντελεστές", creditsText: "Ευχαριστούμε τον StripesVr!", updates: "Ενημερώσεις", online: "Σε σύνδεση", hubOnline: "Hub: Σε σύνδεση" },
    cs: { bio: "Solo Quest Modder a Vývojář Her", moddedApks: "Modované APK", tagDiscord: "ZDARMA PŘES DISCORD", discordCommunity: "Discord Komunita", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "ZDARMA", tvMenuPCVR: "TvMenuPCVR", tagPaid: "PLACENÉ / PŘES DISCORD", moddedGtag: "Modovaný Gtag od Tvman", faqTitle: "Často Kladené Otázky", faqDesc: "Najděte odpovědi níže!", q1Name: "Otázka: Jak stáhnout APK?", q1Val: "Odpověď: Přes náš Discord.", q2Name: "Otázka: Je TvMenu Lib zdarma?", q2Val: "Odpověď: Ano!", q3Name: "Otázka: Kdy vyjde TvMenuPCVR?", q3Val: "Odpověď: Brzy.", q4Name: "Otázka: Podpora?", q4Val: "Odpověď: Discord.", creditsTitle: "Kredity", creditsText: "Díky StripesVr za vytvoření prvního hubu!", updates: "Aktualizace", online: "Online", hubOnline: "Hub: Online" },
    hu: { bio: "Solo Quest Modder és Játékfejlesztő", moddedApks: "Modolt APK-k", tagDiscord: "INGYEN DISCORDON KERESZTÜL", discordCommunity: "Discord Közösség", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "INGYENES", tvMenuPCVR: "TvMenuPCVR", tagPaid: "FIZETŐS / DISCORD", moddedGtag: "Modolt Gtag Tvmantól", faqTitle: "Gyakran Ismételt Kérdések", faqDesc: "Találj választ alább!", q1Name: "K: Hogyan tölthetem le az APK-kat?", q1Val: "V: Discord szerverünkön keresztül.", q2Name: "K: Ingyenes a TvMenu Lib?", q2Val: "V: Igen!", q3Name: "K: Mikor jelenik meg a TvMenuPCVR?", q3Val: "V: Hamarosan.", q4Name: "K: Támogatás?", q4Val: "V: Discord.", creditsTitle: "Készítők", creditsText: "Köszönet StripesVr-nek!", updates: "Frissítések", online: "Online", hubOnline: "Hub: Online" },
    ro: { bio: "Modder Solo Quest și Creator de Jocuri", moddedApks: "APK-uri Modificate", tagDiscord: "GRATUIT PRIN DISCORD", discordCommunity: "Comunitatea Discord", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "GRATUIT", tvMenuPCVR: "TvMenuPCVR", tagPaid: "PLÁTIT / PRIN DISCORD", moddedGtag: "Gtag Modificat de Tvman", faqTitle: "Întrebări Frecvente", faqDesc: "Găsește răspunsuri mai jos!", q1Name: "Î: Cum descarc APK-urile?", q1Val: "R: Prin serverul nostru Discord.", q2Name: "Î: Este TvMenu Lib gratuit?", q2Val: "R: Da!", q3Name: "Î: Când se lansează TvMenuPCVR?", q3Val: "R: În curând.", q4Name: "Î: Suport?", q4Val: "R: Discord.", creditsTitle: "Credite", creditsText: "Credite lui StripesVr!", updates: "Actualizări", online: "Online", hubOnline: "Hub: Online" },
    sk: { bio: "Solo Quest Modder a Vývojár Hier", moddedApks: "Modované APK", tagDiscord: "ZADARMO CEZ DISCORD", discordCommunity: "Discord Komunita", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "ZADARMO", tvMenuPCVR: "TvMenuPCVR", tagPaid: "PLACENÉ / CEZ DISCORD", moddedGtag: "Modovaný Gtag od Tvman", faqTitle: "Často Kladené Otázky", faqDesc: "Odpovede nájdete nižšie!", q1Name: "Otázka: Ako stiahnuť APK?", q1Val: "Odpoveď: Cez náš Discord.", q2Name: "Otázka: Je TvMenu Lib zadarmo?", q2Val: "Odpoveď: Áno!", q3Name: "Otázka: Kedy vyjde TvMenuPCVR?", q3Val: "Odpoveď: Čoskoro.", q4Name: "Otázka: Podpora?", q4Val: "Odpoveď: Discord.", creditsTitle: "Kredity", creditsText: "Vďaka StripesVr!", updates: "Aktualizácie", online: "Online", hubOnline: "Hub: Online" },
    bg: { bio: "Solo Quest Модър и Създател на Игри", moddedApks: "Модифицирани APK", tagDiscord: "БЕЗПЛАТНО ЧРЕЗ DISCORD", discordCommunity: "Discord Общност", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "БЕЗПЛАТНО", tvMenuPCVR: "TvMenuPCVR", tagPaid: "ПЛАТЕНО / DISCORD", moddedGtag: "Модифициран Gtag от Tvman", faqTitle: "Често Задавани Въпроси", faqDesc: "Намерете отговори по-долу!", q1Name: "В: Как да изтегля APK?", q1Val: "О: Чрез нашия Discord сървър.", q2Name: "В: Безплатен ли е TvMenu Lib?", q2Val: "О: Да!", q3Name: "В: Кога излиза TvMenuPCVR?", q3Val: "О: Очаквайте скоро.", q4Name: "В: Поддръжка?", q4Val: "О: Discord.", creditsTitle: "Кредити", creditsText: "Благодарности на StripesVr!", updates: "Обновления", online: "Онлайн", hubOnline: "Hub: Онлайн" },
    hr: { bio: "Solo Quest Modder i Kreator Igara", moddedApks: "Modirani APK", tagDiscord: "BESPLATNO PUTEM DISCORDA", discordCommunity: "Discord Zajednica", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "BESPLATNO", tvMenuPCVR: "TvMenuPCVR", tagPaid: "PLAĆENO / DISCORD", moddedGtag: "Modirani Gtag od Tvmana", faqTitle: "Često Postavljana Pitanja", faqDesc: "Pronađite odgovore u nastavku!", q1Name: "P: Kako preuzeti APK?", q1Val: "O: Putem našeg Discord poslužitelja.", q2Name: "P: Je li TvMenu Lib besplatan?", q2Val: "O: Da!", q3Name: "P: Kada izlazi TvMenuPCVR?", q3Val: "O: Uskoro.", q4Name: "P: Podrška?", q4Val: "O: Discord.", creditsTitle: "Zasluge", creditsText: "Zasluge za StripesVr!", updates: "Ažuriranja", online: "Online", hubOnline: "Hub: Online" },
    sr: { bio: "Solo Quest Модер и Креатор Игара", moddedApks: "Модовани APK", tagDiscord: "БЕСПЛАТНО ПУТЕМ DISCORDA", discordCommunity: "Discord Заједница", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "БЕСПЛАТНО", tvMenuPCVR: "TvMenuPCVR", tagPaid: "ПЛАЋЕНО / DISCORD", moddedGtag: "Модовани Gtag од Tvmana", faqTitle: "Често Постављана Pитања", faqDesc: "Пронађите одговоре испод!", q1Name: "П: Како преузети APK?", q1Val: "О: Путем нашег Discord сервера.", q2Name: "П: Да ли је TvMenu Lib бесплатан?", q2Val: "О: Да!", q3Name: "П: Када излази TvMenuPCVR?", q3Val: "О: Ускоро.", q4Name: "П: Подршка?", q4Val: "О: Discord.", creditsTitle: "Заслуге", creditsText: "Заслуге за StripesVr!", updates: "Ажурирања", online: "Онлине", hubOnline: "Hub: Онлайн" },
    ms: { bio: "Pembuat Mod Quest Solo & Pembuat Permainan", moddedApks: "APK Mod", tagDiscord: "PERCUMA MELALUI DISCORD", discordCommunity: "Komuniti Discord", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "PERCUMA", tvMenuPCVR: "TvMenuPCVR", tagPaid: "BERBAYAR / DISCORD", moddedGtag: "Gtag Mod oleh Tvman", faqTitle: "Soalan Lazim", faqDesc: "Cari jawapan di bawah!", q1Name: "S: Bagaimana cara muat turun APK?", q1Val: "J: Melalui server Discord kami.", q2Name: "S: Adakah TvMenu Lib percuma?", q2Val: "J: Ya!", q3Name: "S: Bilakah TvMenuPCVR akan keluar?", q3Val: "J: Akan datang.", q4Name: "S: Sokongan?", q4Val: "J: Discord.", creditsTitle: "Kredit", creditsText: "Kredit kepada StripesVr!", updates: "Kemas Kini", online: "Dalam Talian", hubOnline: "Hub: Dalam Talian" },
    tl: { bio: "Solo Quest Modder at Game Maker", moddedApks: "Modded APKs", tagDiscord: "LIBRE SA DISCORD", discordCommunity: "Discord Community", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "LIBRE", tvMenuPCVR: "TvMenuPCVR", tagPaid: "MAY BAYAD / DISCORD", moddedGtag: "Modded Gtag ni Tvman", faqTitle: "Mga Madalas Itanong", faqDesc: "Hanapin ang sagot sa ibaba!", q1Name: "T: Paano i-download ang mga APK?", q1Val: "S: Sa pamamagitan ng aming Discord server.", q2Name: "T: Libre ba ang TvMenu Lib?", q2Val: "S: Oo!", q3Name: "T: Kailan lalabas ang TvMenuPCVR?", q3Val: "S: Malapit na.", q4Name: "T: Suporta?", q4Val: "S: Discord.", creditsTitle: "Mga Kredito", creditsText: "Salamat kay StripesVr!", updates: "Mga Update", online: "Online", hubOnline: "Hub: Online" },
    fa: { bio: "مودر انفرادی کوئست و سازنده بازی", moddedApks: "APKهای مود شده", tagDiscord: "دریافت رایگان از طریق دیسکورد", discordCommunity: "انجمن دیسکورد", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "رایگان", tvMenuPCVR: "TvMenuPCVR", tagPaid: "پولی / دیسکورد", moddedGtag: "Gtag مود شده توسط Tvman", faqTitle: "سوالات متداول", faqDesc: "پاسخ‌ها را در زیر بیابید!", q1Name: "س: چگونه APKها را دانلود کنم؟", q1Val: "ج: از طریق سرور دیسکورد ما.", q2Name: "س: آیا TvMenu Lib رایگان است؟", q2Val: "ج: بله!", q3Name: "س: TvMenuPCVR چه زمانی منتشر می‌شود؟", q3Val: "ج: به زودی.", q4Name: "س: پشتیبانی؟", q4Val: "ج: دیسکورد.", creditsTitle: "اعتبارات", creditsText: "تشکر از StripesVr!", updates: "به‌روزرسانی‌ها", online: "آنلاین", hubOnline: "هاب: آنلاین" },
    he: { bio: "מודר קווסט יחיד ויוצר משחקים", moddedApks: "APK מותאמים", tagDiscord: "חינם דרך דיסקורד", discordCommunity: "קהילת דיסקורד", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "חינם", tvMenuPCVR: "TvMenuPCVR", tagPaid: "בתשלום / דיסקורד", moddedGtag: "Gtag מותאם של Tvman", faqTitle: "שאלות נפוצות", faqDesc: "מצא תשובות למטה!", q1Name: "ש: איך מורידים APK?", q1Val: "ת: דרך שרת הדיסקורד שלנו.", q2Name: "ש: האם TvMenu Lib חינמי?", q2Val: "ת: כן!", q3Name: "ש: מתי יצא TvMenuPCVR?", q3Val: "ת: בקרוב.", q4Name: "ש: תמיכה?", q4Val: "ת: דיסקורד.", creditsTitle: "קרדיטים", creditsText: "קרדיט ל-StripesVr!", updates: "עדכונים", online: "מקוון", hubOnline: "רכזת: מקוון" },
    bn: { bio: "সলো কোয়েস্ট মডার এবং গেম মেকার", moddedApks: "মড করা APKs", tagDiscord: "ডিসকর্ডের মাধ্যমে বিনামূল্যে নিন", discordCommunity: "ডিসকর্ড কমিউনিটি", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "বিনামূল্যে", tvMenuPCVR: "TvMenuPCVR", tagPaid: "পেইড / ডিসকর্ড", moddedGtag: "Tvman দ্বারা মড করা Gtag", faqTitle: "সচরাচর জিজ্ঞাসিত প্রশ্ন", faqDesc: "উত্তর নিচে খুঁজুন!", q1Name: "প্র: কীভাবে APK ডাউনলোড করব?", q1Val: "উ: আমাদের ডিসকর্ড সার্ভারের মাধ্যমে।", q2Name: "প্র: TvMenu Lib কি বিনামূল্যে?", q2Val: "উ: হ্যাঁ!", q3Name: "প্র: TvMenuPCVR কবে আসবে?", q3Val: "উ: শীঘ্রই আসছে।", q4Name: "প্র: সহায়তা?", q4Val: "উ: ডিসকর্ড।", creditsTitle: "ক্রেডিট", creditsText: "StripesVr-কে ধন্যবাদ!", updates: "আপডেট", online: "অনলাইন", hubOnline: "হাব: অনলাইন" },
    ur: { bio: "سولو کویسٹ ماڈر اور گیم بنانے والا", moddedApks: "موڈیفائڈ APKs", tagDiscord: "ڈسکارڈ کے ذریعے مفت حاصل کریں", discordCommunity: "ڈسکارڈ کمیونٹی", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "مفت", tvMenuPCVR: "TvMenuPCVR", tagPaid: "پیڈ / ڈسکارڈ", moddedGtag: "Tvman کا موڈ شدہ Gtag", faqTitle: "اکثر پوچھے جانے والے سوالات", faqDesc: "جوابات تلاش کریں!", q1Name: "سوال: اے پی کے کیسے ڈاؤن لوڈ کریں؟", q1Val: "جواب: ہمارے ڈسکارڈ سرور کے ذریعے۔", q2Name: "سوال: کیا TvMenu Lib مفت ہے؟", q2Val: "جواب: ہاں!", q3Name: "سوال: TvMenuPCVR کب آ رہا ہے؟", q3Val: "جواب: جلد آرہا ہے۔", q4Name: "سوال: سپورٹ؟", q4Val: "جواب: ڈسکارڈ۔", creditsTitle: "کریڈٹس", creditsText: "StripesVr کا شکریہ!", updates: "اپڈیٹس", online: "آن لائن", hubOnline: "حب: آن لائن" },
    mr: { bio: "सोलो क्वेस्ट मॉडर आणि गेम मेकर", moddedApks: "मॉड केलेले APKs", tagDiscord: "डिस्कॉर्ड द्वारे मोफत मिळवा", discordCommunity: "डिस्कॉर्ड कम्युनिटी", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "मोफत", tvMenuPCVR: "TvMenuPCVR", tagPaid: "पैसा / डिस्कॉर्ड", moddedGtag: "Tvman द्वारे मॉड Gtag", faqTitle: "सतत विचारले जाणारे प्रश्न", faqDesc: "खाली उत्तरे शोधा!", q1Name: "प्र: APK कसे डाउनलोड करावे?", q1Val: "उ: आमच्या डिस्कॉर्ड सर्व्हरवरून.", q2Name: "प्र: TvMenu Lib मोफत आहे का?", q2Val: "उ: हो!", q3Name: "प्र: TvMenuPCVR कधी येणार?", q3Val: "उ: लवकरच येत आहे.", q4Name: "प्र: सपोर्ट?", q4Val: "उ: डिस्कॉर्ड.", creditsTitle: "श्रेय", creditsText: "StripesVr चे आभार!", updates: "अपडेट्स", online: "ऑनलाइन", hubOnline: "हब: ऑनलाइन" },
    ta: { bio: "சோலோ குவெஸ்ட் மோடர் மற்றும் கேம் மேக்கர்", moddedApks: "மோட் செய்யப்பட்ட APKs", tagDiscord: "டிஸ்கார்ட் மூலம் இலவசமாக பெறுங்கள்", discordCommunity: "டிஸ்கார்ட் சமூகம்", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "இலவசம்", tvMenuPCVR: "TvMenuPCVR", tagPaid: "கட்டணம் / டிஸ்கார்ட்", moddedGtag: "Tvman இன் மோட் செய்யப்பட்ட Gtag", faqTitle: "அடிக்கடி கேட்கப்படும் கேள்விகள்", faqDesc: "பதில்களை கீழே காண்க!", q1Name: "கேள்வி: APK-களை எவ்வாறு பதிவிறக்குவது?", q1Val: "பதில்: எங்கள் டிஸ்கார்ட் சேவையகம் மூலம்.", q2Name: "கேள்வி: TvMenu Lib இலவசமா?", q2Val: "பதில்: ஆம்!", q3Name: "கேள்வி: TvMenuPCVR எгаோழுது வெளியிடப்படுகிறது?", q3Val: "பதில்: விரைவில்.", q4Name: "கேள்வி: உதவி?", q4Val: "பதில்: டிஸ்கார்ட்.", creditsTitle: "மரியாதை", creditsText: "StripesVr-க்கு நன்றி!", updates: "புதுப்பிப்புகள்", online: "ஆன்லைன்", hubOnline: "ஹப்: ஆன்லைன்" },
    te: { bio: "సోలో క్వెస్ట్ మోడర్ మరియు గేమ్ మేకర్", moddedApks: "మోడ్ చేయబడిన APK లు", tagDiscord: "డిస్కార్డ్ ద్వారా ఉచితంగా పొందండి", discordCommunity: "డిస్కార్డ్ కమ్యూనిటీ", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "ఉచితం", tvMenuPCVR: "TvMenuPCVR", tagPaid: "చెల్లించినది / డిస్కార్డ్", moddedGtag: "Tvman ద్వారా మోడ్ చేయబడిన Gtag", faqTitle: "తరచుగా అడిగే ప్రశ్నలు", faqDesc: "సమాధానాలను ఇక్కడ కనుగొనండి!", q1Name: "ప్ర: APKలను ఎలా డౌన్‌లోడ్ చేయాలి?", q1Val: "జ: మా డిస్కార్డ్ సర్వర్ ద్వారా.", q2Name: "ప్ర: TvMenu Lib ఉచితమా?", q2Val: "జ: అవును!", q3Name: "ప్ర: TvMenuPCVR ఎప్పుడు విడుదలవుతుంది?", q3Val: "జ: త్వరలో వస్తుంది.", q4Name: "ప్ర: మద్దతు?", q4Val: "జ: డిస్కార్డ్.", creditsTitle: "క్రెడిట్స్", creditsText: "StripesVr కి ధన్యవాదాలు!", updates: "నవీకరణలు", online: "ఆన్‌లైన్", hubOnline: "హబ్: ఆన్‌లైన్" },
    sw: { bio: "Modder wa Solo Quest na Mtengenezaji wa Michezo", moddedApks: "APK Zilizobadilishwa", tagDiscord: "PATA BILA MALIPO KUPITIA DISCORD", discordCommunity: "Jumuiya ya Discord", tvMenuLib: "TvMenuLib (1.0.0)", tagFree: "BILA MALIPO", tvMenuPCVR: "TvMenuPCVR", tagPaid: "INALIPWA / DISCORD", moddedGtag: "Gtag Iliyobadilishwa na Tvman", faqTitle: "Maswali Yanayoulizwa Mara kwa Mara", faqDesc: "Pata majibu hapa chini!", q1Name: "Swali: Jinsi ya kupakua APK?", q1Val: "Jibu: Kupitia seva yetu ya Discord.", q2Name: "Swali: Je, TvMenu Lib ni bure?", q2Val: "Jibu: Ndiyo!", q3Name: "Swali: TvMenuPCVR itatoka lini?", q3Val: "Jibu: Inakuja hivi karibuni.", q4Name: "Swali: Usaidizi?", q4Val: "Jibu: Discord.", creditsTitle: "Sifa", creditsText: "Asante kwa StripesVr!", updates: "Sasisho", online: "Mtandaoni", hubOnline: "Hub: Mtandaoni" }
};


const extraI18n = {
en:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join discord boi)",surpriseKicker:"DROP",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 is live. PCVR is still in the lab.",surpriseClose:"Enter the hub",patch4:"TvMenuLib 1.0.0, PCVR in-dev tag, rain, drop screen",languageLabel:"Language",inServer:"in server",staticOverlay:"Static overlay",eyebrow:"TVMAN COMMAND",heroTitle:"Mods, libs, and the server — one hub.",heroCopy:"Free APKs and TvMenuLib 1.0.0 through Discord. PCVR is in dev — join Discord, boi.",hotkeys:"Keys: D Discord · L Lib · S static",patchTitle:"Patch notes",widgetTitle:"Live Discord Server Widget",noteSupport:"Support: TvmanMods@proton.me",noteLib:"Lib download opens MediaFire, then join Discord for setup.",libDone:"TvMenuLib 1.0.0 Downloaded!",libBody:"MediaFire started in a new tab. Discord has the setup.",libJoin:"JOIN THE DISCORD TO DO THE REST",updateHistory:"Update History"},
es:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (en dev, métete a Discord boi)",surpriseKicker:"DROP",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 ya está. PCVR sigue en el lab.",surpriseClose:"Entrar al hub",patch4:"TvMenuLib 1.0.0, tag PCVR in-dev, lluvia, pantalla drop",languageLabel:"Idioma",inServer:"en el servidor",staticOverlay:"Estática",heroTitle:"Mods, libs y el servidor — un solo hub.",heroCopy:"APKs gratis y TvMenuLib 1.0.0 por Discord. PCVR en dev — entra a Discord, boi.",hotkeys:"Teclas: D Discord · L Lib · S estática",patchTitle:"Notas del parche",widgetTitle:"Widget de Discord en vivo",noteSupport:"Soporte: TvmanMods@proton.me",noteLib:"La lib se descarga en MediaFire; setup en Discord.",libDone:"¡TvMenuLib 1.0.0 descargada!",libBody:"MediaFire empezó en otra pestaña. El setup está en Discord.",libJoin:"ENTRA AL DISCORD PARA EL RESTO",updateHistory:"Historial de actualizaciones"},
fr:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (en dev, join Discord boi)",surpriseKicker:"DROP",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 est live. PCVR est encore au labo.",surpriseClose:"Entrer dans le hub",patch4:"TvMenuLib 1.0.0, tag PCVR in-dev, pluie, écran drop",languageLabel:"Langue",inServer:"sur le serveur",staticOverlay:"Overlay statique",heroTitle:"Mods, libs et le serveur — un seul hub.",heroCopy:"APK gratuits et TvMenuLib 1.0.0 via Discord. PCVR en dev — join Discord, boi.",hotkeys:"Touches : D Discord · L Lib · S statique",patchTitle:"Notes de patch",widgetTitle:"Widget Discord en direct",libDone:"TvMenuLib 1.0.0 téléchargé !",libJoin:"REJOINS LE DISCORD",updateHistory:"Historique"},
de:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseKicker:"DROP",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 ist live. PCVR ist noch im Lab.",surpriseClose:"Hub betreten",languageLabel:"Sprache",inServer:"im Server",staticOverlay:"Static-Overlay",heroTitle:"Mods, Libs und der Server — ein Hub.",heroCopy:"Gratis APKs und TvMenuLib 1.0.0 über Discord. PCVR in dev — join Discord, boi.",libDone:"TvMenuLib 1.0.0 geladen!",libJoin:"DISCORD JOINEN",updateHistory:"Update-Verlauf",patchTitle:"Patchnotes",widgetTitle:"Live Discord Widget"},
it:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, entra su Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 è live. PCVR è ancora in lab.",surpriseClose:"Entra nell'hub",languageLabel:"Lingua",inServer:"nel server",heroTitle:"Mod, lib e il server — un solo hub.",libJoin:"ENTRA IN DISCORD"},
pt:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (em dev, entra no Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 no ar. PCVR ainda no lab.",surpriseClose:"Entrar no hub",languageLabel:"Idioma",inServer:"no servidor",heroTitle:"Mods, libs e o servidor — um hub.",libJoin:"ENTRA NO DISCORD"},
ru:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (в разработке, в Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 уже здесь. PCVR ещё в лабе.",surpriseClose:"Войти в хаб",languageLabel:"Язык",inServer:"на сервере",heroTitle:"Моды, либы и сервер — один хаб.",libJoin:"В DISCORD"},
ja:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR（開発中、Discordへ boi）",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 公開。PCVR はまだラボ。",surpriseClose:"ハブに入る",languageLabel:"言語",inServer:"サーバー内",libJoin:"DISCORDへ"},
ko:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (개발 중, Discord 가 boi)",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 라이브. PCVR는 아직 랩.",surpriseClose:"허브 입장",languageLabel:"언어",inServer:"서버에서",libJoin:"DISCORD로"},
zh:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR（开发中，去 Discord boi）",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 已上线。PCVR 还在实验室。",surpriseClose:"进入 Hub",languageLabel:"语言",inServer:"在服务器里",libJoin:"去 DISCORD"},
ar:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (قيد التطوير، ادخل ديسكورد boi)",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 نزل. PCVR لسه في المعمل.",surpriseClose:"ادخل الهب",languageLabel:"اللغة",inServer:"في السيرفر",libJoin:"ادخل ديسكورد"},
hi:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (डेव में, Discord आ boi)",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 लाइव है। PCVR अभी लैब में।",surpriseClose:"हब में जाओ",languageLabel:"भाषा",inServer:"सर्वर पर",libJoin:"DISCORD आओ"},
tr:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (dev'de, Discord'a gel boi)",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 yayında. PCVR hâlâ lab'de.",surpriseClose:"Huba gir",languageLabel:"Dil",inServer:"sunucuda",libJoin:"DISCORD'A GEL"},
nl:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 is live. PCVR zit nog in het lab.",surpriseClose:"Hub binnen",languageLabel:"Taal",inServer:"in de server"},
pl:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (w dev, wbij na Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 jest live. PCVR jeszcze w labie.",surpriseClose:"Wejdź do huba",languageLabel:"Język",inServer:"na serwerze"},
vi:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (đang dev, vào Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 đã live. PCVR vẫn trong lab.",surpriseClose:"Vào hub",languageLabel:"Ngôn ngữ",inServer:"trong server"},
th:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (กำลังทำ, เข้า Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 ออกแล้ว PCVR ยังในแล็บ",surpriseClose:"เข้าฮับ",languageLabel:"ภาษา",inServer:"ในเซิร์ฟเวอร์"},
id:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (masih dev, masuk Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 sudah live. PCVR masih di lab.",surpriseClose:"Masuk hub",languageLabel:"Bahasa",inServer:"di server"},
uk:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (в розробці, у Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseBody:"TvMenuLib 1.0.0 уже тут. PCVR ще в лабі.",surpriseClose:"Увійти в хаб",languageLabel:"Мова",inServer:"на сервері"},
sv:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"Gå in i hubben",languageLabel:"Språk",inServer:"på servern"},
no:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"Gå inn i huben",languageLabel:"Språk",inServer:"på serveren"},
da:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"Gå ind i hubben",languageLabel:"Sprog",inServer:"på serveren"},
fi:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"Astu hubiin",languageLabel:"Kieli",inServer:"palvelimella"},
el:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"Μπες στο hub",languageLabel:"Γλώσσα",inServer:"στον server"},
cs:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"Vstoupit do hubu",languageLabel:"Jazyk",inServer:"na serveru"},
hu:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"Belépés a hubba",languageLabel:"Nyelv",inServer:"a szerveren"},
ro:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"Intră în hub",languageLabel:"Limbă",inServer:"pe server"},
sk:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"Vstúpiť do hubu",languageLabel:"Jazyk",inServer:"na serveri"},
bg:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"Влез в хъба",languageLabel:"Език",inServer:"в сървъра"},
hr:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"Uđi u hub",languageLabel:"Jezik",inServer:"na serveru"},
sr:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"Уђи у хаб",languageLabel:"Језик",inServer:"на серверу"},
ms:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"Masuk hub",languageLabel:"Bahasa",inServer:"dalam server"},
tl:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, join Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"Pasok sa hub",languageLabel:"Wika",inServer:"sa server"},
fa:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (در حال ساخت، بیا دیسکورد boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"ورود به هاب",languageLabel:"زبان",inServer:"در سرور"},
he:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (בפיתוח, תיכנס לדיסקורד boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"כניסה להאב",languageLabel:"שפה",inServer:"בשרת"},
bn:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (ডেভে, Discord-এ আয় boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"হাবে ঢোকো",languageLabel:"ভাষা",inServer:"সার্ভারে"},
ur:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (ڈیو میں، Discord آؤ boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"ہب میں داخل",languageLabel:"زبان",inServer:"سرور پر"},
mr:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (डेवमध्ये, Discord वर ये boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"हबमध्ये जा",languageLabel:"भाषा",inServer:"सर्व्हरवर"},
ta:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (டெவ், Discord வா boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"ஹப்பில் நுழை",languageLabel:"மொழி",inServer:"சர்வரில்"},
te:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (డెవ్‌లో, Discord రా boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"హబ్‌లోకి",languageLabel:"భాష",inServer:"సర్వర్‌లో"},
sw:{versionChip:"HUB v4.0.0",tvMenuLib:"TvMenuLib (1.0.0)",tvMenuPCVR:"TvMenuPCVR (in dev, ingia Discord boi)",surpriseTitle:"HUB v4.0.0",surpriseClose:"Ingia hub",languageLabel:"Lugha",inServer:"kwenye server"}
};

const extraFallback = extraI18n.en;
Object.keys(translations).forEach((lang) => {
    const pack = extraI18n[lang] || extraFallback;
    translations[lang] = Object.assign({}, extraFallback, pack, translations[lang], extraI18n[lang] || {});
});

function changeLanguage(lang) {
    const t = Object.assign({}, extraFallback, translations[lang] || translations.en);
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (t[key]) el.textContent = t[key];
    });
    document.documentElement.lang = lang || 'en';
}

